import { ProductoDTO } from '@/components/catalogo/ProductoCard';

/**
 * Catálogo Oficial de Productos Reales de Steffen Cosmética Capilar.
 * Utiliza exclusivamente las líneas originales de la marca y las imágenes locales
 * cargadas en el portal (/assets/profesionales/).
 */
export const PRODUCTOS_REALES_STEFFEN: ProductoDTO[] = [
  {
    id: 'steffen-biphase-keratina',
    codigo: 'BIPH-KER-250',
    nombre: 'Bi-Phase Keratina Steffen',
    categoria: 'Bi-phase',
    subcategoria: 'Desenredantes y Restauración',
    descripcion:
      'Tratamiento bifásico desenredante e hidratante con keratina pura. Restaura en el acto cabellos sensibilizados o expuestos a procesos químicos.',
    imagen: '/assets/profesionales/biphase32-4.jpg',
    presentacion: '250 ml',
    precioPss: 14200,
    precioEcommerce: 19900,
    precioVisible: 19900,
    tipoPrecio: 'PUBLICO',
    precioProfesionalBloqueado: null,
    stock: 50,
    activo: true,
    ordenVisualizacion: 1,
    destacado: true,
    recomendado: true,
  },
  {
    id: 'steffen-cristal-semi-de-lino',
    codigo: 'CRIS-LINO-60',
    nombre: 'Cristal Semi de Lino Steffen',
    categoria: 'Sérums y Cristales',
    subcategoria: 'Reparador de Puntas',
    descripcion:
      'Tratamiento concentrado reparador de puntas abiertas con aceite noble de lino. Aporta brillo espejo, máxima suavidad y control antifrizz instantáneo.',
    imagen: '/assets/profesionales/sin-titulo-2.jpg',
    presentacion: '60 ml',
    precioPss: 12500,
    precioEcommerce: 17500,
    precioVisible: 17500,
    tipoPrecio: 'PUBLICO',
    precioProfesionalBloqueado: null,
    stock: 45,
    activo: true,
    ordenVisualizacion: 2,
    destacado: true,
    recomendado: true,
  },
  {
    id: 'steffen-biphase-semi-de-lino',
    codigo: 'BIPH-LINO-250',
    nombre: 'Bi-Phase Semi de Lino Steffen',
    categoria: 'Bi-phase',
    subcategoria: 'Nutrición y Brillo',
    descripcion:
      'Acondicionador desenredante bifásico enriquecido con extracto de semillas de lino y filtro solar UV para protección térmica y brillo diario.',
    imagen: '/assets/profesionales/biphase32-10.jpg',
    presentacion: '250 ml',
    precioPss: 14200,
    precioEcommerce: 19900,
    precioVisible: 19900,
    tipoPrecio: 'PUBLICO',
    precioProfesionalBloqueado: null,
    stock: 60,
    activo: true,
    ordenVisualizacion: 3,
    destacado: true,
    recomendado: false,
  },
  {
    id: 'steffen-mascara-nutritiva-keratina',
    codigo: 'MASC-KER-500',
    nombre: 'Máscara Nutritiva Keratina Steffen',
    categoria: 'Tratamientos',
    subcategoria: 'Nutrición Profunda',
    descripcion:
      'Baño de crema hiper-nutritivo con keratina vegetal para cabellos secos, porosos o químicamente tratados. Regenera la fibra desde el interior.',
    imagen: '/assets/profesionales/placa-2.jpg',
    presentacion: '500 g',
    precioPss: 21500,
    precioEcommerce: 29900,
    precioVisible: 29900,
    tipoPrecio: 'PUBLICO',
    precioProfesionalBloqueado: null,
    stock: 35,
    activo: true,
    ordenVisualizacion: 4,
    destacado: true,
    recomendado: true,
  },
  {
    id: 'steffen-bioesfera-keratina',
    codigo: 'BIO-KER-250',
    nombre: 'Bio-Esfera Keratina Reparadora',
    categoria: 'Tratamientos',
    subcategoria: 'Microesferas Restauradoras',
    descripcion:
      'Fluido concentrado con microesferas activas de keratina pura para nutrición profunda, sellado de cutículas y peinabilidad profesional.',
    imagen: '/assets/profesionales/biphase32 (4).jpg',
    presentacion: '250 ml',
    precioPss: 16800,
    precioEcommerce: 23500,
    precioVisible: 23500,
    tipoPrecio: 'PUBLICO',
    precioProfesionalBloqueado: null,
    stock: 30,
    activo: true,
    ordenVisualizacion: 5,
    destacado: true,
    recomendado: false,
  },
  {
    id: 'steffen-shampoo-semi-de-lino',
    codigo: 'SHA-LINO-1000',
    nombre: 'Shampoo Semi de Lino Salón',
    categoria: 'Shampoo',
    subcategoria: 'Lavado Profesional',
    descripcion:
      'Fórmula profesional para bacha y lavacabezas con semillas de lino naturales. Limpia suavemente sin resecar y equilibra la hidratación capilar.',
    imagen: '/assets/profesionales/7.jpg',
    presentacion: '1000 ml',
    precioPss: 18900,
    precioEcommerce: 26500,
    precioVisible: 26500,
    tipoPrecio: 'PUBLICO',
    precioProfesionalBloqueado: null,
    stock: 40,
    activo: true,
    ordenVisualizacion: 6,
    destacado: true,
    recomendado: false,
  },
];
